import type {
  Activity,
  AnalyticsMetric,
  Application,
  ApplicationStatus,
  Deadline,
  PrepTask,
  ResumeVersion,
} from "@/lib/types";

export const applicationStatuses: ApplicationStatus[] = [
  "Wishlist",
  "Applying",
  "Applied",
  "OA",
  "Interview",
  "Final Round",
  "Offer",
  "Rejected",
];

export const applications: Application[] = [
  {
    id: "jpmorgan-chase-swe",
    company: "JPMorgan Chase",
    role: "Software Engineer Intern",
    location: "New York, NY",
    status: "Applied",
    dateApplied: "Jun 18",
    deadline: "Jul 08",
    source: "Handshake",
    notes: "Tailored finance resume with payments project and Java experience.",
    resume: "Finance Resume",
    category: "Finance",
  },
  {
    id: "google-step",
    company: "Google",
    role: "STEP Intern",
    location: "Mountain View, CA",
    status: "OA",
    dateApplied: "Jun 11",
    deadline: "Jul 01",
    source: "Referral",
    notes: "OA invite received. Review arrays, strings, and recursion patterns.",
    resume: "General SWE Resume",
    category: "Big Tech",
  },
  {
    id: "meta-swe",
    company: "Meta",
    role: "Software Engineer Intern",
    location: "Menlo Park, CA",
    status: "Interview",
    dateApplied: "Jun 04",
    deadline: "Jul 03",
    source: "Careers site",
    notes: "Recruiter screen done. Technical round needs graph review.",
    resume: "General SWE Resume",
    category: "Big Tech",
  },
  {
    id: "bloomberg-swe",
    company: "Bloomberg",
    role: "Software Engineer Intern",
    location: "New York, NY",
    status: "Final Round",
    dateApplied: "May 29",
    deadline: "Jul 10",
    source: "Campus event",
    notes: "Strong C++ angle. Prepare market data system discussion.",
    resume: "Finance Resume",
    category: "Finance",
  },
  {
    id: "capital-one-tech",
    company: "Capital One",
    role: "Technology Intern",
    location: "McLean, VA",
    status: "Offer",
    dateApplied: "May 12",
    source: "Referral",
    notes: "Offer deadline next week. Compare team matching and location.",
    resume: "Backend Resume",
    category: "Fintech",
  },
  {
    id: "datadog-swe",
    company: "Datadog",
    role: "Software Engineer Intern",
    location: "New York, NY",
    status: "Applying",
    deadline: "Jul 14",
    source: "Careers site",
    notes: "Need observability keyword pass before submitting.",
    resume: "Backend Resume",
    category: "Data",
  },
  {
    id: "stripe-backend",
    company: "Stripe",
    role: "Backend Engineering Intern",
    location: "San Francisco, CA",
    status: "Wishlist",
    deadline: "Jul 18",
    source: "Careers site",
    notes: "Draft answers around API design and payment reliability.",
    resume: "Backend Resume",
    category: "Fintech",
  },
  {
    id: "jane-street-swe",
    company: "Jane Street",
    role: "Software Engineering Intern",
    location: "New York, NY",
    status: "Rejected",
    dateApplied: "May 06",
    source: "Careers site",
    notes: "Rejected after resume screen. Rework systems project bullets.",
    resume: "Quant Resume",
    category: "Finance",
  },
];

export const resumes: ResumeVersion[] = [
  {
    id: "general-swe",
    name: "General SWE Resume",
    lastUpdated: "Jun 24",
    applicationsUsedFor: 12,
    keywordMatchScore: 86,
    status: "Active",
    focus: "Full-stack internships and general backend roles",
  },
  {
    id: "quant",
    name: "Quant Resume",
    lastUpdated: "Jun 17",
    applicationsUsedFor: 4,
    keywordMatchScore: 72,
    status: "Draft",
    focus: "Trading firms, probability, systems, and C++",
  },
  {
    id: "ai-ml",
    name: "AI/ML Resume",
    lastUpdated: "Jun 21",
    applicationsUsedFor: 6,
    keywordMatchScore: 81,
    status: "Active",
    focus: "ML projects, model evaluation, and data pipelines",
  },
  {
    id: "backend",
    name: "Backend Resume",
    lastUpdated: "Jun 26",
    applicationsUsedFor: 9,
    keywordMatchScore: 91,
    status: "Active",
    focus: "APIs, distributed systems, databases, and reliability",
  },
  {
    id: "finance",
    name: "Finance Resume",
    lastUpdated: "Jun 19",
    applicationsUsedFor: 7,
    keywordMatchScore: 79,
    status: "Draft",
    focus: "Banking, fintech, Java, risk systems, and data platforms",
  },
];

export const prepTasks: PrepTask[] = [
  {
    id: "daily-coding",
    title: "Longest Substring Without Repeating Characters",
    type: "Coding",
    difficulty: "Medium",
    topic: "Sliding window",
    targetTime: "35 min",
    status: "In Progress",
  },
  {
    id: "behavioral-star",
    title: "Tell me about a time you solved a difficult technical problem.",
    type: "Behavioral",
    topic: "STAR storytelling",
    targetTime: "20 min",
    status: "Not Started",
  },
  {
    id: "system-url-shortener",
    title: "Design a URL shortener",
    type: "System Design",
    topic: "Caching, database schema, API design",
    targetTime: "45 min",
    status: "Not Started",
  },
];

export const activities: Activity[] = [
  {
    id: "activity-1",
    label: "Meta interview moved forward",
    detail: "Technical interview scheduled for next Thursday.",
    time: "2h ago",
    tone: "success",
  },
  {
    id: "activity-2",
    label: "Google OA due soon",
    detail: "Complete the assessment before the July 1 deadline.",
    time: "Yesterday",
    tone: "warning",
  },
  {
    id: "activity-3",
    label: "Backend resume improved",
    detail: "Keyword match rose from 84% to 91%.",
    time: "2d ago",
    tone: "info",
  },
  {
    id: "activity-4",
    label: "Jane Street archived",
    detail: "Rejected after resume screen. Add follow-up notes.",
    time: "4d ago",
    tone: "danger",
  },
];

export const deadlines: Deadline[] = [
  {
    id: "deadline-1",
    company: "Google",
    title: "OA submission",
    due: "Jul 01",
    urgency: "High",
  },
  {
    id: "deadline-2",
    company: "Meta",
    title: "Technical interview prep",
    due: "Jul 03",
    urgency: "High",
  },
  {
    id: "deadline-3",
    company: "Capital One",
    title: "Offer response window",
    due: "Jul 07",
    urgency: "Medium",
  },
  {
    id: "deadline-4",
    company: "Bloomberg",
    title: "Final round packet",
    due: "Jul 10",
    urgency: "Medium",
  },
];

export const analyticsMetrics: AnalyticsMetric[] = [
  {
    id: "response-rate",
    label: "Response rate",
    value: "38%",
    helper: "3 responses from 8 tracked applications",
    change: "+8% vs last month",
    tone: "green",
  },
  {
    id: "oa-conversion",
    label: "OA conversion",
    value: "25%",
    helper: "2 OAs from applications submitted",
    change: "+1 active OA",
    tone: "cyan",
  },
  {
    id: "interview-conversion",
    label: "Interview conversion",
    value: "13%",
    helper: "1 interview stage after OA or screen",
    change: "Needs more volume",
    tone: "amber",
  },
  {
    id: "offers",
    label: "Offers",
    value: "1",
    helper: "Capital One offer in review",
    change: "Decision due Jul 07",
    tone: "purple",
  },
  {
    id: "rejections",
    label: "Rejections",
    value: "1",
    helper: "Jane Street resume screen",
    change: "Resume update queued",
    tone: "red",
  },
];

export const applicationsOverTime = [
  { label: "Week 1", value: 3 },
  { label: "Week 2", value: 5 },
  { label: "Week 3", value: 7 },
  { label: "Week 4", value: 8 },
];

export const prepConsistency = [
  { label: "Mon", value: 70 },
  { label: "Tue", value: 88 },
  { label: "Wed", value: 62 },
  { label: "Thu", value: 95 },
  { label: "Fri", value: 80 },
  { label: "Sat", value: 45 },
  { label: "Sun", value: 76 },
];
