import type {
  Activity,
  AnalyticsMetric,
  Application,
  ApplicationStatus,
  Deadline,
  PrepTask,
  ResumeVersion,
} from "@/lib/types";

export const applicationStatuses: ApplicationStatus[] = [
  "Wishlist",
  "Applying",
  "Applied",
  "OA",
  "Interview",
  "Final Round",
  "Offer",
  "Rejected",
];

export const applications: Application[] = [
  {
    id: "jpmorgan-chase-swe",
    company: "JPMorgan Chase",
    role: "Software Engineer Intern",
    location: "New York, NY",
    status: "Applied",
    dateApplied: "2026-06-18",
    deadline: "2026-07-08",
    source: "Handshake",
    resumeUsed: "Finance Resume",
    jobUrl: "https://careers.jpmorgan.com/us/en/students/programs/software-engineer-summer",
    recruiterName: "Maya Chen",
    recruiterEmail: "maya.chen@example.com",
    salaryRange: "$45-55/hr",
    priority: "High",
    notes: "Tailored finance resume with payments project and Java experience.",
    tags: ["finance", "java", "payments"],
    createdAt: "2026-06-14T14:30:00.000Z",
    updatedAt: "2026-06-18T16:20:00.000Z",
    category: "Finance",
  },
  {
    id: "google-step",
    company: "Google",
    role: "STEP Intern",
    location: "Mountain View, CA",
    status: "OA",
    dateApplied: "2026-06-11",
    deadline: "2026-07-01",
    source: "Referral",
    resumeUsed: "General SWE Resume",
    jobUrl: "https://www.google.com/about/careers/applications/jobs/results/",
    recruiterName: "Priya Shah",
    recruiterEmail: "priya.shah@example.com",
    salaryRange: "$48-60/hr",
    priority: "High",
    notes: "OA invite received. Review arrays, strings, and recursion patterns.",
    tags: ["big-tech", "oa", "referral"],
    createdAt: "2026-06-08T12:00:00.000Z",
    updatedAt: "2026-06-24T18:15:00.000Z",
    category: "Big Tech",
  },
  {
    id: "meta-swe",
    company: "Meta",
    role: "Software Engineer Intern",
    location: "Menlo Park, CA",
    status: "Interview",
    dateApplied: "2026-06-04",
    deadline: "2026-07-03",
    source: "Careers site",
    resumeUsed: "General SWE Resume",
    jobUrl: "https://www.metacareers.com/jobs/",
    recruiterName: "Jordan Lee",
    recruiterEmail: "jordan.lee@example.com",
    salaryRange: "$50-62/hr",
    priority: "High",
    notes: "Recruiter screen done. Technical round needs graph review.",
    tags: ["graphs", "technical-round", "big-tech"],
    createdAt: "2026-06-01T17:45:00.000Z",
    updatedAt: "2026-06-25T13:10:00.000Z",
    category: "Big Tech",
  },
  {
    id: "bloomberg-swe",
    company: "Bloomberg",
    role: "Software Engineer Intern",
    location: "New York, NY",
    status: "Final Round",
    dateApplied: "2026-05-29",
    deadline: "2026-07-10",
    source: "Campus event",
    resumeUsed: "Finance Resume",
    jobUrl: "https://careers.bloomberg.com/job/search",
    recruiterName: "Evan Brooks",
    recruiterEmail: "evan.brooks@example.com",
    salaryRange: "$46-58/hr",
    priority: "High",
    notes: "Strong C++ angle. Prepare market data system discussion.",
    tags: ["finance", "cpp", "final-round"],
    createdAt: "2026-05-25T11:00:00.000Z",
    updatedAt: "2026-06-27T09:35:00.000Z",
    category: "Finance",
  },
  {
    id: "capital-one-tech",
    company: "Capital One",
    role: "Technology Intern",
    location: "McLean, VA",
    status: "Offer",
    dateApplied: "2026-05-12",
    deadline: "2026-07-07",
    source: "Referral",
    resumeUsed: "Backend Resume",
    jobUrl: "https://www.capitalonecareers.com/",
    recruiterName: "Alex Rivera",
    recruiterEmail: "alex.rivera@example.com",
    salaryRange: "$42-50/hr",
    priority: "High",
    notes: "Offer deadline next week. Compare team matching and location.",
    tags: ["offer", "backend", "fintech"],
    createdAt: "2026-05-10T15:10:00.000Z",
    updatedAt: "2026-06-26T20:00:00.000Z",
    category: "Fintech",
  },
  {
    id: "datadog-swe",
    company: "Datadog",
    role: "Software Engineer Intern",
    location: "New York, NY",
    status: "Applying",
    dateApplied: "",
    deadline: "2026-07-14",
    source: "Careers site",
    resumeUsed: "Backend Resume",
    jobUrl: "https://www.datadoghq.com/careers/",
    recruiterName: "",
    recruiterEmail: "",
    salaryRange: "$48-58/hr",
    priority: "Medium",
    notes: "Need observability keyword pass before submitting.",
    tags: ["observability", "backend", "draft"],
    createdAt: "2026-06-20T10:30:00.000Z",
    updatedAt: "2026-06-28T12:45:00.000Z",
    category: "Data",
  },
  {
    id: "stripe-backend",
    company: "Stripe",
    role: "Backend Engineering Intern",
    location: "San Francisco, CA",
    status: "Wishlist",
    dateApplied: "",
    deadline: "2026-07-18",
    source: "Careers site",
    resumeUsed: "Backend Resume",
    jobUrl: "https://stripe.com/jobs",
    recruiterName: "",
    recruiterEmail: "",
    salaryRange: "$55-65/hr",
    priority: "Medium",
    notes: "Draft answers around API design and payment reliability.",
    tags: ["payments", "api-design", "wishlist"],
    createdAt: "2026-06-22T08:20:00.000Z",
    updatedAt: "2026-06-22T08:20:00.000Z",
    category: "Fintech",
  },
  {
    id: "jane-street-swe",
    company: "Jane Street",
    role: "Software Engineering Intern",
    location: "New York, NY",
    status: "Rejected",
    dateApplied: "2026-05-06",
    deadline: "",
    source: "Careers site",
    resumeUsed: "Quant Resume",
    jobUrl: "https://www.janestreet.com/join-jane-street/open-roles/",
    recruiterName: "",
    recruiterEmail: "",
    salaryRange: "$60-75/hr",
    priority: "Low",
    notes: "Rejected after resume screen. Rework systems project bullets.",
    tags: ["quant", "rejected", "resume-screen"],
    createdAt: "2026-05-02T12:00:00.000Z",
    updatedAt: "2026-06-12T19:30:00.000Z",
    category: "Finance",
  },
];

export const resumes: ResumeVersion[] = [
  {
    id: "general-swe",
    name: "General SWE Resume",
    targetRole: "Software Engineer",
    description: "Broad full-stack and backend version for general software engineering roles.",
    status: "Active",
    lastUpdated: "2026-06-24T14:30:00.000Z",
    applicationsUsed: 12,
    keywordMatchScore: 86,
    tags: ["Full-stack", "Backend", "TypeScript"],
    strengths: ["Product delivery", "API design", "Cross-functional work"],
    weaknesses: ["Few scale metrics"],
    missingKeywords: ["Kafka", "Kubernetes"],
    suggestedImprovement: "Add production scale and latency metrics to the first project.",
    notes: "Default version for roles without a narrow specialty.",
    fileName: "aryan-general-swe.pdf",
    createdAt: "2026-05-18T13:00:00.000Z",
    updatedAt: "2026-06-24T14:30:00.000Z",
  },
  {
    id: "quant",
    name: "Quant Resume",
    targetRole: "Quantitative Developer",
    description: "Systems, probability, and performance-focused version for trading firms.",
    status: "Draft",
    lastUpdated: "2026-06-17T16:15:00.000Z",
    applicationsUsed: 4,
    keywordMatchScore: 72,
    tags: ["C++", "Systems", "Probability"],
    strengths: ["Algorithmic thinking", "Performance engineering"],
    weaknesses: ["Limited finance context"],
    missingKeywords: ["Market microstructure", "Low latency"],
    suggestedImprovement: "Quantify runtime improvements in the simulation project.",
    notes: "Needs one more finance-oriented project bullet before activation.",
    fileName: "aryan-quant-draft.docx",
    createdAt: "2026-06-03T10:00:00.000Z",
    updatedAt: "2026-06-17T16:15:00.000Z",
  },
  {
    id: "ai-ml",
    name: "AI/ML Resume",
    targetRole: "Machine Learning Engineer",
    description: "Model evaluation, applied ML projects, and reliable data pipeline experience.",
    status: "Active",
    lastUpdated: "2026-06-21T12:45:00.000Z",
    applicationsUsed: 6,
    keywordMatchScore: 81,
    tags: ["Python", "ML", "Data pipelines"],
    strengths: ["Model evaluation", "Data engineering"],
    weaknesses: ["Deployment detail"],
    missingKeywords: ["MLflow", "Feature store"],
    suggestedImprovement: "Explain how the model was monitored after deployment.",
    notes: "Use for applied ML and data-heavy product teams.",
    fileName: "aryan-ml.pdf",
    createdAt: "2026-05-26T09:20:00.000Z",
    updatedAt: "2026-06-21T12:45:00.000Z",
  },
  {
    id: "backend",
    name: "Backend Resume",
    targetRole: "Backend Engineer",
    description: "APIs, distributed systems, databases, reliability, and measurable performance.",
    status: "Active",
    lastUpdated: "2026-06-26T18:10:00.000Z",
    applicationsUsed: 9,
    keywordMatchScore: 91,
    tags: ["Distributed systems", "Postgres", "Reliability"],
    strengths: ["API design", "Database systems", "Operational ownership"],
    weaknesses: ["Testing details"],
    missingKeywords: ["Contract testing"],
    suggestedImprovement: "Add test coverage and incident response details to the API project.",
    notes: "Strongest current version for infrastructure-minded product teams.",
    fileName: "aryan-backend-v4.pdf",
    createdAt: "2026-05-20T11:30:00.000Z",
    updatedAt: "2026-06-26T18:10:00.000Z",
  },
  {
    id: "finance",
    name: "Finance Resume",
    targetRole: "Software Engineer, Financial Systems",
    description: "Java, data platforms, risk systems, and reliable financial workflows.",
    status: "Draft",
    lastUpdated: "2026-06-19T15:05:00.000Z",
    applicationsUsed: 7,
    keywordMatchScore: 79,
    tags: ["Java", "Fintech", "Data platforms"],
    strengths: ["Transaction systems", "Data modeling"],
    weaknesses: ["Domain metrics"],
    missingKeywords: ["Risk controls", "Reconciliation"],
    suggestedImprovement: "Connect project outcomes to correctness and financial risk reduction.",
    notes: "Draft for banks and later-stage fintech companies.",
    fileName: "aryan-finance-draft.pdf",
    createdAt: "2026-06-01T14:00:00.000Z",
    updatedAt: "2026-06-19T15:05:00.000Z",
  },
];

export const prepTasks: PrepTask[] = [
  {
    id: "daily-coding",
    title: "Longest Substring Without Repeating Characters",
    type: "Coding",
    difficulty: "Medium",
    topic: "Sliding window",
    targetTime: "35 min",
    status: "In Progress",
  },
  {
    id: "behavioral-star",
    title: "Tell me about a time you solved a difficult technical problem.",
    type: "Behavioral",
    topic: "STAR storytelling",
    targetTime: "20 min",
    status: "Not Started",
  },
  {
    id: "system-url-shortener",
    title: "Design a URL shortener",
    type: "System Design",
    topic: "Caching, database schema, API design",
    targetTime: "45 min",
    status: "Not Started",
  },
];

export const activities: Activity[] = [
  {
    id: "activity-1",
    label: "Meta interview moved forward",
    detail: "Technical interview scheduled for next Thursday.",
    time: "2h ago",
    tone: "success",
  },
  {
    id: "activity-2",
    label: "Google OA due soon",
    detail: "Complete the assessment before the July 1 deadline.",
    time: "Yesterday",
    tone: "warning",
  },
  {
    id: "activity-3",
    label: "Backend resume improved",
    detail: "Keyword match rose from 84% to 91%.",
    time: "2d ago",
    tone: "info",
  },
  {
    id: "activity-4",
    label: "Jane Street archived",
    detail: "Rejected after resume screen. Add follow-up notes.",
    time: "4d ago",
    tone: "danger",
  },
];

export const deadlines: Deadline[] = [
  {
    id: "deadline-1",
    company: "Google",
    title: "OA submission",
    due: "Jul 01",
    urgency: "High",
  },
  {
    id: "deadline-2",
    company: "Meta",
    title: "Technical interview prep",
    due: "Jul 03",
    urgency: "High",
  },
  {
    id: "deadline-3",
    company: "Capital One",
    title: "Offer response window",
    due: "Jul 07",
    urgency: "Medium",
  },
  {
    id: "deadline-4",
    company: "Bloomberg",
    title: "Final round packet",
    due: "Jul 10",
    urgency: "Medium",
  },
];

export const analyticsMetrics: AnalyticsMetric[] = [
  {
    id: "response-rate",
    label: "Response rate",
    value: "38%",
    helper: "3 responses from 8 tracked applications",
    change: "+8% vs last month",
    tone: "green",
  },
  {
    id: "oa-conversion",
    label: "OA conversion",
    value: "25%",
    helper: "2 OAs from applications submitted",
    change: "+1 active OA",
    tone: "cyan",
  },
  {
    id: "interview-conversion",
    label: "Interview conversion",
    value: "13%",
    helper: "1 interview stage after OA or screen",
    change: "Needs more volume",
    tone: "amber",
  },
  {
    id: "offers",
    label: "Offers",
    value: "1",
    helper: "Capital One offer in review",
    change: "Decision due Jul 07",
    tone: "purple",
  },
  {
    id: "rejections",
    label: "Rejections",
    value: "1",
    helper: "Jane Street resume screen",
    change: "Resume update queued",
    tone: "red",
  },
];

export const applicationsOverTime = [
  { label: "Week 1", value: 3 },
  { label: "Week 2", value: 5 },
  { label: "Week 3", value: 7 },
  { label: "Week 4", value: 8 },
];

export const prepConsistency = [
  { label: "Mon", value: 70 },
  { label: "Tue", value: 88 },
  { label: "Wed", value: 62 },
  { label: "Thu", value: 95 },
  { label: "Fri", value: 80 },
  { label: "Sat", value: 45 },
  { label: "Sun", value: 76 },
];
