"use client";

import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { Brain, Play, Save, Sparkles, X } from "lucide-react";
import type { BehavioralEvaluation, BehavioralPracticeResult, BehavioralQuestion, PrepStatus } from "@/lib/types";
import { behavioralCompetencies, competencyLabel } from "@/lib/behavioral-coach";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Field, Textarea } from "@/components/prep/coding-problem-modal";
import { PrepStatusSelect } from "@/components/prep/prep-status-select";
import { useModalBehavior } from "@/hooks/use-modal-behavior";

type Props = {
  question: BehavioralQuestion | null;
  onClose: () => void;
  onSave: (question: BehavioralQuestion) => void;
  onEvaluate: (storyId: string, competencyFocus?: string) => Promise<{ evaluation: BehavioralEvaluation; story: BehavioralQuestion }>;
  onHistory: (storyId: string) => Promise<BehavioralEvaluation[]>;
  onPractice: (input: { storyId: string; competency: string; prompt: string; answer: string }) => Promise<BehavioralPracticeResult>;
};

export function BehavioralAnswerDrawer(props: Props) {
  if (!props.question) return null;
  return <BehavioralDrawerContent key={props.question.id} {...props} question={props.question} />;
}

function BehavioralDrawerContent({ question, onClose, onSave, onEvaluate, onHistory, onPractice }: Omit<Props, "question"> & { question: BehavioralQuestion }) {
  const dialogRef = useModalBehavior(); const [form, setForm] = useState(question); const [focus, setFocus] = useState(question.competencyTags?.[0] ?? "ownership");
  const [history, setHistory] = useState<BehavioralEvaluation[]>([]); const [latest, setLatest] = useState<BehavioralEvaluationResultState>(question.latestEvaluation ? { evaluation: question.latestEvaluation, comparison: question.trendSummary ?? null, provider: "saved" } : null);
  const [evaluating, setEvaluating] = useState(false); const [practicing, setPracticing] = useState(false); const [error, setError] = useState("");
  const [prompt, setPrompt] = useState("Tell me about a time you showed ownership."); const [answer, setAnswer] = useState("");
  useEffect(() => { let active = true; void onHistory(question.id).then((rows) => { if (active) setHistory(rows); }).catch(() => undefined); return () => { active = false; }; }, [onHistory, question.id]);
  function update<K extends keyof BehavioralQuestion>(key: K, value: BehavioralQuestion[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function toggleCompetency(value: string) { const current = form.competencyTags ?? []; update("competencyTags", current.includes(value) ? current.filter((item) => item !== value) : [...current, value]); }
  async function evaluate() { setEvaluating(true); setError(""); try { const result = await onEvaluate(question.id, focus); setForm(result.story); setLatest({ evaluation: result.evaluation.evaluation, comparison: result.evaluation.comparison, provider: result.evaluation.provider }); setHistory((current) => [result.evaluation, ...current.filter((item) => item.id !== result.evaluation.id)]); } catch (cause) { setError(cause instanceof Error ? cause.message : "Behavioral evaluation could not be completed."); } finally { setEvaluating(false); } }
  async function practice() { if (answer.trim().length < 20) { setError("Write at least a few sentences before evaluating this practice answer."); return; } setPracticing(true); setError(""); try { const result = await onPractice({ storyId: question.id, competency: focus, prompt, answer }); setLatest({ evaluation: result.evaluation, comparison: null, provider: result.id.startsWith("behavioral-practice-") ? "local" : "cloud" }); setAnswer(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Practice evaluation could not be completed."); } finally { setPracticing(false); } }
  const completeness = form.starCompleteness ?? { score: [form.starSituation, form.starTask, form.starAction, form.starResult].filter((value) => value.trim()).length * 25, signals: [], sections: {}, wordCount: 0, schemaVersion: "star-completeness-v1" };
  return createPortal(<div className="fixed inset-0 z-50 overflow-hidden bg-slate-950/70 backdrop-blur-sm" onMouseDown={(event) => { if (event.target === event.currentTarget && !evaluating && !practicing) onClose(); }}><aside className="page-enter ml-auto flex h-[100dvh] w-full max-w-3xl flex-col border-l border-white/10 bg-[#1b1d2b] shadow-2xl shadow-black/30" ref={dialogRef} role="dialog" aria-modal="true" aria-label="Behavioral Coach story"><div className="flex shrink-0 items-start justify-between border-b border-white/10 px-4 py-4 sm:px-6 sm:py-5"><div><div className="flex items-center gap-2"><h2 className="text-xl font-semibold text-white">Behavioral Coach</h2><Badge tone={form.readinessStatus === "interview_ready" ? "green" : "purple"}>{competencyLabel(form.readinessStatus ?? "draft")}</Badge></div><p className="mt-1 max-w-xl text-sm leading-6 text-slate-400">{question.question}</p></div><button aria-label="Close behavioral answer" disabled={evaluating || practicing} className="rounded-xl border border-white/10 bg-white/5 p-2 text-slate-400 transition hover:bg-white/10 hover:text-white disabled:opacity-50" onClick={onClose} type="button"><X className="size-4" /></button></div><div className="min-h-0 flex-1 space-y-6 overflow-y-auto overscroll-contain px-4 py-5 pb-10 sm:px-6">
    <section><h3 className="text-sm font-semibold text-white">Story overview</h3><div className="mt-3 grid gap-4 sm:grid-cols-2"><Field label="Category"><Input data-autofocus value={form.category} onChange={(event) => update("category", event.target.value)} /></Field><div><span className="mb-1.5 block text-xs font-medium text-slate-500">Status</span><PrepStatusSelect label="Behavioral answer status" value={form.status} onChange={(status: PrepStatus) => update("status", status)} /></div></div><div className="mt-4"><p className="text-xs font-medium text-slate-500">Competencies</p><div className="mt-2 flex flex-wrap gap-2">{behavioralCompetencies.map((item) => <button className={`rounded-md border px-2 py-1 text-xs transition ${(form.competencyTags ?? []).includes(item) ? "border-indigo-400/40 bg-indigo-400/15 text-indigo-100" : "border-white/10 text-slate-400 hover:text-white"}`} key={item} onClick={() => toggleCompetency(item)} type="button">{competencyLabel(item)}</button>)}</div></div></section>
    <section className="space-y-4"><h3 className="text-sm font-semibold text-white">STAR story</h3><Field label="Situation"><Textarea rows={4} value={form.starSituation} onChange={(value) => update("starSituation", value)} /></Field><Field label="Task"><Textarea rows={3} value={form.starTask} onChange={(value) => update("starTask", value)} /></Field><Field label="Action"><Textarea rows={5} value={form.starAction} onChange={(value) => update("starAction", value)} /></Field><Field label="Result"><Textarea rows={4} value={form.starResult} onChange={(value) => update("starResult", value)} /></Field><Field label={`Confidence score: ${form.confidenceScore}/5`}><input aria-label="Confidence score" className="h-2 w-full cursor-pointer accent-indigo-400" max={5} min={1} type="range" value={form.confidenceScore} onChange={(event) => update("confidenceScore", Number(event.target.value))} /></Field></section>
    <section className="rounded-xl border border-white/10 bg-white/[0.025] p-4"><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold text-white">STAR completeness</h3><p className="mt-1 text-xs text-slate-500">Deterministic checks run before any AI evaluation.</p></div><span className="font-semibold text-white">{completeness.score}%</span></div><Progress className="mt-3" value={completeness.score} tone="purple" /><div className="mt-3 flex flex-wrap gap-2">{completeness.signals.length ? completeness.signals.map((signal) => <Badge key={signal} tone="amber">{competencyLabel(signal)}</Badge>) : <Badge tone="green"><CheckIcon /> Core STAR checks passed</Badge>}</div></section>
    <section><div className="flex flex-col gap-3 sm:flex-row sm:items-end"><Field label="Evaluation focus"><select className="h-10 w-full rounded-lg border border-white/10 bg-slate-950/30 px-3 text-sm text-white outline-none focus:border-indigo-400/50" value={focus} onChange={(event) => setFocus(event.target.value)}>{behavioralCompetencies.map((item) => <option key={item} value={item}>{competencyLabel(item)}</option>)}</select></Field><Button disabled={evaluating} onClick={() => void evaluate()} variant="primary"><Sparkles className="size-4" />{evaluating ? "Evaluating story..." : "Evaluate story"}</Button></div>{error ? <p className="mt-3 rounded-lg border border-rose-300/20 bg-rose-300/10 px-3 py-2 text-sm text-rose-200">{error}</p> : null}{latest ? <EvaluationResult value={latest} /> : <p className="mt-3 text-sm text-slate-500">Evaluate this saved story to establish a comparable baseline. Scores are coaching guidance, not interview guarantees.</p>}</section>
    <section className="rounded-xl border border-white/10 bg-white/[0.025] p-4"><div className="flex items-center gap-2"><Play className="size-4 text-violet-300" /><h3 className="text-sm font-semibold text-white">Focused practice</h3></div><div className="mt-4 space-y-3"><Field label="Prompt"><Input value={prompt} onChange={(event) => setPrompt(event.target.value)} /></Field><Field label="Your answer"><Textarea rows={6} value={answer} onChange={setAnswer} /></Field><Button disabled={practicing} onClick={() => void practice()} variant="ghost"><Brain className="size-4" />{practicing ? "Evaluating practice..." : "Evaluate practice answer"}</Button></div></section>
    {history.length ? <section><h3 className="text-sm font-semibold text-white">Evaluation history</h3><div className="mt-3 space-y-2">{history.slice(0, 6).map((item) => <div className="flex items-center justify-between rounded-lg border border-white/10 px-3 py-2 text-sm" key={item.id}><div><p className="text-slate-200">{competencyLabel(item.competencyFocus ?? "general")}</p><p className="text-xs text-slate-500">{new Date(item.createdAt).toLocaleDateString()} · {competencyLabel(item.comparison.status)}</p></div><span className="text-xs text-slate-400">{item.provider === "local" || item.provider === "deterministic" ? "Simulated/rules" : item.provider}</span></div>)}</div></section> : null}
  </div><div className="flex shrink-0 justify-end gap-2 border-t border-white/10 bg-[#1b1d2b] px-4 py-4 sm:px-6"><Button disabled={evaluating || practicing} onClick={onClose} variant="ghost">Cancel</Button><Button disabled={evaluating || practicing} onClick={() => onSave(form)} variant="primary"><Save className="size-4" />Save story</Button></div></aside></div>, document.body);
}

type BehavioralEvaluationResultState = { evaluation: NonNullable<BehavioralQuestion["latestEvaluation"]>; comparison: BehavioralEvaluation["comparison"] | null; provider: string } | null;
function EvaluationResult({ value }: { value: NonNullable<BehavioralEvaluationResultState> }) { const scores = value.evaluation.qualityScores; const overall = Math.round(Object.values(scores).reduce((sum, score) => sum + score, 0) / Object.values(scores).length * 20); return <div className="mt-4 space-y-4 rounded-xl border border-indigo-300/15 bg-indigo-300/[0.05] p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase text-indigo-200">Latest evaluation</p><p className="mt-1 text-xs text-slate-500">{value.provider === "deterministic" || value.provider === "local" ? "Simulated deterministic guidance" : "AI-assisted coaching guidance"}</p></div><span className="text-2xl font-semibold text-white">{overall}%</span></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{Object.entries(scores).map(([key, score]) => <div className="rounded-lg bg-black/10 p-2" key={key}><p className="text-xs text-slate-500">{competencyLabel(key)}</p><p className="font-semibold text-white">{score}/5</p></div>)}</div>{value.evaluation.strengths.length ? <List title="Recurring strengths" values={value.evaluation.strengths} /> : null}{value.evaluation.weaknesses.length ? <List title="Recurring weaknesses" values={value.evaluation.weaknesses} /> : null}{value.evaluation.recommendedRevision.length ? <List title="Recommended revisions" values={value.evaluation.recommendedRevision} /> : null}{value.comparison ? <p className="text-xs text-slate-400">Comparison: {competencyLabel(value.comparison.status)}{value.comparison.improvedAreas.length ? ` · Improved ${value.comparison.improvedAreas.map(competencyLabel).join(", ")}` : ""}</p> : null}</div>; }
function List({ title, values }: { title: string; values: string[] }) { return <div><p className="text-xs font-semibold uppercase text-slate-500">{title}</p><ul className="mt-2 space-y-1 text-sm leading-6 text-slate-300">{values.slice(0, 4).map((item) => <li key={item}>• {item}</li>)}</ul></div>; }
function CheckIcon() { return <span aria-hidden="true">✓</span>; }
