import { CalendarDays, Target } from "lucide-react";
import type { MomentumSummary } from "@/lib/dashboard-utils";
import type { WeeklyPrepDay } from "@/lib/types";
import { Card, CardContent, CardHeader } from "@/components/ui/card";

export function MomentumCard({ momentum, days }: { momentum: MomentumSummary; days: WeeklyPrepDay[] }) {
  return <Card className="premium-hover"><CardHeader><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-semibold text-white">Recruiting Momentum</h2><p className="mt-1 text-sm text-slate-500">A transparent score from weekly activity and active pipeline signals.</p></div><Target className="size-5 text-cyan-200" /></div></CardHeader><CardContent><div className="flex flex-col items-start gap-5 sm:flex-row sm:items-end">
    <div className="relative flex size-32 shrink-0 items-center justify-center rounded-full p-2" style={{ background: `conic-gradient(from 180deg, #7f8fce 0 ${momentum.score}%, #2a2d3e ${momentum.score}% 100%)` }}><div className="flex size-full flex-col items-center justify-center rounded-full border border-slate-700/45 bg-[#1b1d2b]"><span className="text-3xl font-semibold text-white">{momentum.score}</span><span className="text-xs text-slate-500">score</span></div></div>
    <div className="min-w-0 flex-1"><div className="flex items-center gap-2 text-sm font-medium text-white"><CalendarDays className="size-4 text-indigo-300" />{momentum.label}</div><p className="mt-2 text-sm leading-6 text-slate-500">{momentum.explanation}</p><div className="mt-4 grid grid-cols-7 gap-2">{days.map((day, index) => <div className="flex flex-col items-center gap-2" key={day.date}><div className="flex h-12 w-full items-end rounded-full bg-slate-800/80"><div className="w-full rounded-full bg-indigo-400/80" style={{ height: `${momentum.dailyValues[index] ?? 12}%` }} /></div><span className="text-[11px] text-slate-500">{new Intl.DateTimeFormat("en-US", { weekday: "narrow" }).format(new Date(`${day.date}T12:00:00`))}</span></div>)}</div></div>
  </div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Applications", momentum.applicationsThisWeek], ["Prep tasks", momentum.prepThisWeek], ["Active signals", momentum.activeSignals], ["Resume updates", momentum.resumeUpdates]].map(([label, value]) => <div className="rounded-xl border border-white/10 bg-white/[0.025] p-3" key={String(label)}><div className="text-lg font-semibold text-white">{value}</div><div className="text-xs text-slate-500">{label}</div></div>)}</div></CardContent></Card>;
}
